patchesStrategicMerge:
- deployment.yaml

namespace: fmeza-prd

images:
- name: argogotest
  newName: mezafrank/argogotest
  newTag: v0.0.13
- name: goapi
  newName: mezafrank/goapi
  newTag: v0.0.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
