patchesStrategicMerge:
- deployment.yaml

images:
- name: argogotest
  newName: mezafrank/argogotest
  newTag: 0.0.9
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
