patches:
- deployment.yaml

namespace: fmeza-int

images:
- name: argogotest
  newName: docker.io/mezafrank/argogotest
  newTag: 0.0.8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/