apiVersion: apps/v1
kind: Deployment
metadata:
  name: argogotest
  labels:
    app: argogotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argogotest
  template:
    metadata:
      labels:
        app: argogotest
    spec:
      containers:
        - name: argogotest
          image: argogotest:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi