patchesStrategicMerge:
- deployment.yaml

namespace: fmeza-prd

images:
- name: goapi
  newName: mezafrank/goapi
  newTag: 0.0.8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
