patchesStrategicMerge:
- deployment.yaml

namespace: fmeza-int

images:
- name: goapi
  newName: mezafrank/goapi
  newTag: v.0.0.6
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
