patches:
- deployment.yaml

namespace: fmeza-int

images:
- name: goapi
  newName: docker.io/mezafrank/goapi
  newTag: 0.0.1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/